
name: CI

on:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job cagn access it
      - uses: actions/checkout@v3

  
      - name: build docker images
        run: docker build -t trailimage .
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker images
        run: |
          docker tag trailimage akash300/trailimage
          docker push akash300/trailimage
